# Macro file for the 
# initialization of G4GeneralParticleSource

#
#
/control/verbose 2
/run/verbose 1
/testem/phys/addPhysics  emstandard_opt1

/run/initialize

/gps/energy 80 GeV
/gps/particle geantino

# longitudinal beam
/gps/position 0.0 0.0 -0.2 m

/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/halfx 1 cm
/gps/pos/halfy 1 cm

/gps/ang/type beam2d
#/gps/ang/sigma_x 5. mrad
#/gps/ang/sigma_y 5. mrad
#/gps/ang/rot1 0. 0. 1.
/gps/direction 0. 0.018 1.


/run/beamOn 20
